### PR TITLE
Fix compile warning

### PR DESCRIPTION
**Pull request by c4710n**
Elixir 1.11 is coming. 

A lot of libs have fixed the warning, so do we. 😃 

This PR:
1. migrates from `applications` to `extra_applications`
2. upgrades outdated deps

### CODE REVIEW

**Review by achempion — APPROVED** [review]

**Comment by Nitrino** [comment]
Hi @achempion, 
Can you please merge this PR?

**Comment by achempion** [comment]
I see you've included `eex` in extra applications. Do we really need it here?

**Comment by c4710n** [comment]
> I see you've included `eex` in extra applications. Do we really need it here?

I have remove the commit adding `:eex` to `extra_applications`.

> I remembered that `:eex` is required when I was fixing the warning. But, It's been so long that I can't remember why. ;(

**Comment by c4710n** [comment]
I found the problem about `:eex` again.

When removing `:eex` from `extra_applications` and compile project with `MIX_ENV=prod mix compile`, it will report:
```
warning: EEx.compile_string/2 defined in application :eex is used by the current application but the current application does not directly depend on :eex. To fix this, you must do one of:

  1. If :eex is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :eex is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :eex, you may optionally skip this warning by adding [xref: [exclude: EEx]] to your "def project" in mix.exs

  lib/mix/tasks/g.ex:66: Mix.Tasks.Waffle.G
```

This is why I add `:eex` before.

**Pull request merged**
