### PR TITLE
Handle special S3 escaping

### PR DESCRIPTION
**Pull request by dmarkow**
https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html

S3 has a handful of special characters that `URI.encode/2` doesn't properly escape. Most notably, filenames with `+` result in broken urls.

This change overrides the matcher on `URI.encode` to explicitly escape the characters referenced by the S3 documentation above, and falls back to the default checker for all other characters.

Also, I moved the escaping to just the `s3_key` portion, since a host/bucket on S3 shouldn't have any characters that need escaping. All tests are passing.

### CODE REVIEW

**Comment by achempion** [comment]
Hi Dylan,

Thank you for the pull request. I've tested it and found a peculiar demeanour of the ExAws library.

This code will create a file for S3 bucket, but it "escapes" `+` sign for a space.

```elixir
ExAws.S3.put_object(bucket, "data+my.txt", "content") |> ExAws.request!
```

will create a `data my.txt` file.

If we try to upload the file with `+` symbol to another S3 compatible service as Linode, we'll get an error.

**Comment by dmarkow** [comment]
If that's the case, then it's surprising that when I use waffle to upload a file that has plus signs in it, the plus signs are *not* being replaced with spaces. Unless something in waffle's code is escaping the plus signs during the S3 upload, but not during the URL generation.

I'll need to dig into this some more when I have some time...

**Comment by achempion** [comment]
I've upgraded the ex_aws to the latest version and the issue with `+` escaping got resolved.

I had `2.1.1` and can't reproduce this with `2.1.2`.

**Comment by achempion** [comment]
It seems like if we have a separate `jason` dependency,  `mix` will resolve `jason` to `1.2.0` and `ex_aws` to `2.1.1` because it doesn't have version restriction for `jason`.

If we remove `jason` from dependency list we'll get the latest `ex_aws` version `2.1.2` because of [version restriction](https://diff.hex.pm/diff/ex_aws/2.1.1..2.1.2#84732810--38).

**Comment by dmarkow** [comment]
ex_aws 2.1.3 (released yesterday) relaxes the Jason dependency.

**Comment by achempion** [comment]
Thank you for your contributon 💛

**Pull request merged**
